import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ScrollSpyProvider } from '@/components/ScrollSpyPrivider';
import { Analytics } from '@vercel/analytics/next';
const roboto = Roboto_Mono({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Kenny Quach',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased overflow-x-hidden`}>
        <ScrollSpyProvider>
          <div className='fixed'>
            <Navbar />
          </div>
          <div className='p-5 max-w-[1500px] mx-auto'>{children}</div>
          <Analytics />
        </ScrollSpyProvider>
      </body>
    </html>
  );
}
